# Generated by Django 5.0.6 on 2026-01-17 09:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('patient_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=50)),
                ('employee_type', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('PENSIONER', 'Pensioner'), ('FAMILY_PENSIONER', 'Family Pensioner'), ('ARTISAN', 'Artisan')], max_length=30)),
                ('relationship', models.CharField(choices=[('SELF', 'Self'), ('DEPENDENT', 'Dependent')], max_length=20)),
                ('credit_card_number', models.CharField(max_length=50)),
                ('ip_number', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=15)),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('disease_details', models.TextField()),
                ('admission_date', models.DateField()),
                ('discharge_date', models.DateField()),
                ('gross_claimed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gross_approved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('IN_PROCESS', 'In Process'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BillDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('ID_CARD', 'Employee / Pensioner / Artisan ID Card'), ('CC_CARD', 'Approved CC Card'), ('FINAL_BILL', 'Final Hospital Bill'), ('DETAIL_BILL', 'Detailed Hospital Bill'), ('PHARMACY', 'Pharmacy Bill'), ('INVOICE', 'Invoice'), ('DISCHARGE', 'Discharge Summary'), ('OTHER', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to='medical_bills/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hospitals.bill')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('tier', models.CharField(choices=[('TIER1', 'Tier-I'), ('TIER2', 'Tier-II'), ('TIER3', 'Tier-III')], max_length=10)),
                ('district', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('pan_number', models.CharField(blank=True, max_length=20)),
                ('gst_number', models.CharField(blank=True, max_length=30)),
                ('cin_number', models.CharField(blank=True, max_length=30)),
                ('valid_upto', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='hospitals.hospital'),
        ),
        migrations.CreateModel(
            name='SanctionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, unique=True)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('sanctioned_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('pdf_file', models.FileField(upload_to='sanction_orders/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sanction_order', to='hospitals.bill')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='hospitals.scheme'),
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_service_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('claimed_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('claimed_quantity', models.PositiveIntegerField()),
                ('claimed_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('approved_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('approved_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('comments', models.TextField(blank=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='hospitals.bill')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitals.service')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('FORWARDED', 'Forwarded'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('action_at', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_history', to='hospitals.bill')),
            ],
        ),
    ]
