# Generated by Django 4.2.27 on 2026-01-13 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdocument',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Associated Billing Head', null=True, on_delete=django.db.models.deletion.PROTECT, to='hospitals.service'),
        ),
    ]
