# Generated by Django 4.2.27 on 2026-01-11 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(unique=True)),
                ('role_name', models.CharField(max_length=100)),
                ('can_reject', models.BooleanField(default=False)),
                ('can_approve_final', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SanctionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=255)),
                ('patient_name', models.CharField(max_length=255)),
                ('claimed_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sanctioned_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CLARIFICATION', 'Clarification Needed')], default='PENDING', max_length=20)),
                ('is_limit_exceeded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sanction_requests', to=settings.AUTH_USER_MODEL)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sanction_request', to='hospitals.bill')),
                ('current_step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pending_requests', to='workflow.workflowstep')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SanctionLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('PENSIONER', 'Pensioner'), ('FAMILY_PENSIONER', 'Family Pensioner'), ('ARTISAN', 'Artisan')], max_length=50)),
                ('limit_type', models.CharField(choices=[('MINOR', 'Minor'), ('MAJOR', 'Major'), ('SELF_FUNDING', 'Self Funding')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'unique_together': {('category', 'limit_type')},
            },
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('FORWARD', 'Forward'), ('REJECT', 'Reject'), ('APPROVE', 'Approve (Final)'), ('CLARIFY', 'Seek Clarification'), ('RESPOND', 'Respond to Clarification')], max_length=20)),
                ('comments', models.TextField()),
                ('approved_amount_at_stage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workflow.sanctionrequest')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow.workflowstep')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
